require('dotenv').config();
const pool = require('./pool');

const EN_TO_MM = {
  // Meta / multi-answer
  'All are correct':            'အားလုံးမှန်ကန်သည်',
  'Both A and B':               'A နှင့် B နှစ်ခုစလုံး',
  'Both B and C':               'B နှင့် C နှစ်ခုစလုံး',
  'Both are correct':           'နှစ်ခုစလုံး မှန်ကန်သည်',
  'Neither is correct':         'တစ်ခုမှ မမှန်ကန်ပါ',

  // Directions / positions
  'Above':                      'အပေါ်',
  'Below':                      'အောက်',
  'Up':                         'အပေါ်',
  'Up/Above':                   'အပေါ်',
  'Down':                       'အောက်',
  'Down/Below':                 'အောက်',
  'Left':                       'ဘယ်',
  'Right':                      'ညာ',
  'Inside':                     'အထဲ',
  'Inside/Middle':              'အထဲ / အလယ်',
  'Outside':                    'အပြင်',
  'Before':                     'ရှေ့ / အရင်',
  'Before/Front':               'ရှေ့ / အရင်',
  'After/Behind':               'နောက်',
  'North':                      'မြောက်',
  'South':                      'တောင်',
  'East':                       'အရှေ့',
  'West':                       'အနောက်',

  // Elements / Nature
  'Fire':                       'မီး',
  'Water':                      'ရေ',
  'Earth':                      'မြေ',
  'Earth/Soil':                 'မြေ',
  'Wind':                       'လေ',
  'Wood':                       'သစ်',
  'Tree/Wood':                  'သစ်ပင်',
  'Gold/Money':                 'ရွှေ / ပိုက်ဆံ',
  'Silver':                     'ငွေ',
  'Copper':                     'ကြေး',
  'Iron':                       'သံ',
  'Mountain':                   'တောင်',
  'River':                      'မြစ်',
  'Sea':                        'ပင်လယ်',
  'Sky/Heaven':                 'ကောင်းကင်',
  'Flower':                     'ပန်း',
  'Snow':                       'နှင်း',
  'Rain':                       'မိုး',
  'Cloud':                      'တိမ်',
  'Weather':                    'ရာသီဥတု',
  'Nature':                     'သဘာဝ',
  'Artificial':                 'လူလုပ်',
  'Environment':                'ပတ်ဝန်းကျင်',
  'Garden':                     'ဥယျာဉ်',

  // Colors
  'Black':                      'မည်း',
  'White':                      'ဖြူ',
  'Red':                        'နီ',
  'Blue':                       'ပြာ',

  // Body parts
  'Eye':                        'မျက်စိ',
  'Ear':                        'နား',
  'Mouth':                      'ပါးစပ်',
  'Hand':                       'လက်',
  'Foot':                       'ခြေ',
  'Foot/Leg':                   'ခြေ',
  'Head':                       'ခေါင်း',
  'Face':                       'မျက်နှာ',
  'Nose':                       'နှာ',

  // Family
  'Father':                     'အဖေ',
  'Mother':                     'အမေ',
  'Brother':                    'ညီအစ်ကို',
  'Sister':                     'ညီမ / အစ်မ',
  'Older brother':              'အစ်ကို',
  'Younger brother':            'ညီ',
  'Older sister':               'အစ်မ',
  'Younger sister':             'ညီမ',

  // Places
  'House':                      'အိမ်',
  'School':                     'ကျောင်း',
  'Hospital':                   'ဆေးရုံ',
  'Shop/Store':                 'ဆိုင်',
  'Company':                    'ကုမ္ပဏီ',
  'Government':                 'အစိုးရ',
  'Country':                    'နိုင်ငံ',
  'City':                       'မြို့',
  'Town':                       'မြို့ကလေး',
  'World':                      'ကမ္ဘာ',

  // Everyday items
  'Pen':                        'ဘောပင်',
  'Book':                       'စာအုပ်',
  'Paper':                      'စာရွက်',
  'Desk':                       'စားပွဲ',
  'Textbook':                   'ကျောင်းသုံးစာအုပ်',
  'Dictionary':                 'အဘိဓာန်',
  'Reference':                  'ကိုးကားစာ',
  'Photo':                      'ဓာတ်ပုံ',

  // Time words
  'Every':                      'တိုင်း',
  'Next':                       'နောက်',
  'Last':                       'ပြီးခဲ့သော',
  'This':                       'ဤ / ဒီ',

  // WH-words
  'Who':                        'ဘယ်သူ',
  'What':                       'ဘာ',
  'Where':                      'ဘယ်မှာ',
  'When':                       'ဘယ်အချိန်',

  // Size / quantity adjectives
  'Big':                        'ကြီးသော',
  'Big/Large':                  'ကြီးသော',
  'Small':                      'သေးသော',
  'Small/Little':               'သေးသော',
  'Long':                       'ရှည်သော',
  'Short':                      'တိုသော',
  'Wide':                       'ကျယ်သော',
  'Narrow':                     'ကျဉ်းသော',
  'Heavy':                      'လေးသော',
  'Light':                      'ပေါ့သော',
  'Tiny':                       'သေးငယ်လွန်းသော',
  'Enormous/Vast':              'ကြီးမားသော',
  'Slight':                     'နည်းငယ်',
  'Gradual':                    'တဖြည်းဖြည်း',
  'Normal':                     'ပုံမှန်',
  'Average':                    'ပျမ်းမျှ',
  'Simple':                     'ရိုးရှင်းသော',
  'Complex':                    'ရှုပ်ထွေးသော',
  'Quick':                      'မြန်သော',
  'Rough':                      'ကြမ်းတမ်းသော',
  'Obvious':                    'ထင်ရှားသော',

  // Quality adjectives
  'New':                        'အသစ်',
  'Old':                        'ဟောင်းသော',
  'Cheap':                      'ဈေးသက်သာသော',
  'Expensive':                  'ဈေးကြီးသော',
  'Expensive/Tall':             'ဈေးကြီး / မြင့်သော',
  'Low/Cheap':                  'ဈေးနှိမ့် / ဈေးသက်သာ',
  'Famous':                     'ကျော်ကြားသော',
  'Unknown':                    'မသိ / မကျော်',
  'Convenient':                 'အဆင်ပြေသော',
  'Inconvenient':               'အဆင်မပြေသော',
  'Important/Precious':         'အရေးကြီးသော',
  'Useless':                    'အသုံးမဝင်သော',
  'Unnecessary':                'မလိုအပ်သော',
  'Necessary/Needed':           'လိုအပ်သော',
  'Possible':                   'ဖြစ်နိုင်သော',
  'Impossible':                 'မဖြစ်နိုင်သော',
  'Safe':                       'ဘေးကင်းသော',
  'Dangerous':                  'အန္တရာယ်ရှိသော',
  'Scary':                      'ကြောက်စရာ',
  'Strong':                     'ခိုင်မာသော',
  'Weak':                       'အားနည်းသော',
  'Difficult':                  'ခက်ခဲသော',
  'Easy':                       'လွယ်ကူသော',
  'Flexible':                   'ပြောင်းလွယ်သော',
  'Rigid':                      'တင်းမာသော',
  'Efficient':                  'ထိရောက်သော',
  'Wasteful':                   'ဖြုန်းတီးသော',
  'Abstract':                   'သဘောတရားဆိုင်ရာ',
  'Concrete/Specific':          'တိကျသော',
  'General':                    'အထွေထွေ',
  'Vague':                      'မရှင်းလင်းသော',
  'Vague/Ambiguous':            'မရှင်းလင်းသော',
  'Clear':                      'ရှင်းလင်းသော',
  'Certain':                    'သေချာသော',
  'Accurate':                   'တိကျသော',
  'Subtle':                     'မထင်မရှားသော',
  'Subtle/Delicate':            'မထင်မရှားသော',
  'Hidden':                     'ဝှက်ထားသော',
  'Remarkable/Prominent':       'ထင်ရှားသော',
  'Remarkable/Striking':        'ထင်ရှားသော',
  'Ordinary':                   'ပုံမှန်',
  'Usual':                      'ရိုးရိုး',
  'Special':                    'ထူးခြားသော',
  'Meticulous/Elaborate':       'စေ့စပ်သေချာသော',

  // Feelings / states
  'Happy':                      'ပျော်ရွှင်သော',
  'Sad':                        'ဝမ်းနည်းသော',
  'Angry':                      'ဒေါသထွက်သော',
  'Fear':                       'ကြောက်ရွံ့ခြင်း',
  'Hate':                       'မုန်းတီးခြင်း',
  'Love':                       'ချစ်ခြင်း',
  'Tired':                      'ပင်ပန်းနေသော',
  'Busy':                       'အလုပ်များသော',
  'Healthy/Fine':               'ကျန်းမာသော',
  'Sick':                       'နာမကျန်းသော',
  'Boredom':                    'ငြီးငွေ့ခြင်း',
  'Interest':                   'စိတ်ဝင်စားမှု',
  'Excitement':                 'တက်ကြွမှု',
  'Peace':                      'ငြိမ်းချမ်းမှု',
  'Harmony':                    'သဟဇာတ',

  // Academic / study
  'Study':                      'ပညာသင်ယူမှု',
  'Work':                       'အလုပ်',
  'Practice':                   'လေ့ကျင့်ခြင်း',
  'Test':                       'စာမေးပွဲ',
  'Lesson':                     'သင်ခန်းစာ',
  'Homework':                   'အိမ်စာ',
  'Review':                     'ပြန်လည်သုံးသပ်ခြင်း',
  'Preparation':                'ပြင်ဆင်ခြင်း',
  'Knowledge':                  'ဗဟုသုတ',
  'Intelligence':               'ဉာဏ်ရည်',
  'Wisdom':                     'ပညာ',
  'Logic':                      'ယုတ္တိဗေဒ',
  'Philosophy':                 'ဒဿနိကဗေဒ',
  'Science':                    'သိပ္ပံ',
  'Psychology':                 'စိတ်ပညာ',
  'History':                    'သမိုင်း',
  'Geography':                  'ဘူမိဗေဒ',
  'Math':                       'သင်္ချာ',
  'Art':                        'အနုပညာ',
  'Literature':                 'စာပေ',
  'Language':                   'ဘာသာစကား',
  'Culture':                    'ယဉ်ကျေးမှု',
  'Ethics':                     'ကျင့်ဝတ်',

  // Social / Abstract
  'Society':                    'လူ့အဖွဲ့အစည်း',
  'Politics':                   'နိုင်ငံရေး',
  'Economy':                    'စီးပွားရေး',
  'Law':                        'ဥပဒေ',
  'Rule':                       'စည်းကမ်း',
  'Custom':                     'ထုံးတမ်းစဉ်လာ',
  'System/Institution':         'စနစ်',
  'Technology':                 'နည်းပညာ',

  // Concepts / abstract nouns
  'Effort':                     'ကြိုးပမ်းအားထုတ်မှု',
  'Talent':                     'ဆုကောင်းချီး / ပြေးကောင်း',
  'Luck':                       'ကံကောင်းခြင်း',
  'Chance':                     'အခွင့်အရေး',
  'Success':                    'အောင်မြင်ခြင်း',
  'Failure':                    'ကျရှုံးခြင်း',
  'Experience':                 'အတွေ့အကြုံ',
  'Memory':                     'မှတ်ဥာဏ်',
  'Record':                     'မှတ်တမ်း',
  'Plan':                       'အစီအစဉ်',
  'Dream':                      'အိပ်မက် / ရည်မှန်းချက်',
  'Idea':                       'အကြံဉာဏ်',
  'Summary':                    'အကျဉ်းချုပ်',
  'Introduction':               'မိတ်ဆက်ခြင်း',
  'Example':                    'ဥပမာ',
  'Concept/Notion':             'သဘောတရား',
  'Essence/True nature':        'အနှစ်သာရ',
  'Appearance':                 'အပြင်ပန်',
  'Surface':                    'မျက်နှာပြင်',
  'Feature':                    'ထူးခြားချက်',
  'Opinion':                    'အမြင်သဘောထား',
  'Viewpoint':                  'အမြင်',
  'Conclusion':                 'နိဂုံးချုပ်',
  'Basis/Grounds':              'အခြေအမြစ်',
  'Cause':                      'အကြောင်းရင်း',
  'Cause/Reason':               'အကြောင်းရင်း',
  'Reason':                     'အကြောင်းပြချက်',
  'Effect':                     'သက်ရောက်မှု',
  'Influence/Effect':           'သက်ရောက်မှု',
  'Result':                     'ရလဒ်',
  'Result/Outcome':             'ရလဒ်',
  'Process':                    'လုပ်ငန်းစဉ်',
  'Method':                     'နည်းလမ်း',
  'Direction':                  'ဦးတည်ချက်',
  'Distance':                   'အကွာအဝေး',
  'Separation':                 'ခွဲခြားမှု',
  'Difference':                 'ကွာခြားချက်',
  'Similarity':                 'တူညီမှု',
  'Comparison':                 'နှိုင်းယှဉ်ခြင်း',
  'Competition':                'ပြိုင်ဆိုင်မှု',
  'Agreement':                  'သဘောတူညီမှု',
  'Agreement/Approval':         'သဘောတူညီမှု / ခွင့်ပြုမှု',
  'Approval':                   'ခွင့်ပြုမှု',
  'Opposition':                 'ဆန့်ကျင်မှု',
  'Opposition/Opposite':        'ဆန့်ကျင်မှု',
  'Neutrality':                 'ကြားနေမှု',
  'Contradiction':              'ဆန့်ကျင်ကွဲလွဲမှု',
  'Conflict/Struggle':          'ပဋိပက္ခ',
  'Prejudice/Bias':             'ဘက်လိုက်မှု',
  'Insight':                    'ထိုးထွင်းသိမြင်မှု',
  'Observation':                'လေ့လာဆင်ခြင်မှု',
  'Investigation':              'စုံစမ်းစစ်ဆေးမှု',
  'Experiment':                 'စမ်းသပ်မှု',
  'Assumption':                 'ယူဆချက်',
  'Memorization':               'မှတ်သား',
  'Grasp/Comprehension':        'နားလည်သဘောပေါက်မှု',
  'Consideration/Care':         'ဂရုစိုက်မှု',
  'Awareness':                  'သတိရှိမှု',
  'Attention':                  'အာရုံ',
  'Ignorance':                  'မသိမနား',
  'Tendancy/Trend':             'ခေတ်ရေစီးကြောင်း',
  'Tendency/Trend':             'ခေတ်ရေစီးကြောင်း',
  'Habit':                      'အလေ့အကျင့်',
  'Pattern':                    'ပုံစံ',
  'Category':                   'အမျိုးအစား',
  'Subject':                    'ဘာသာရပ်',
  'Topic':                      'ခေါင်းစဉ်',
  'Field/Area':                 'နယ်ပယ်',
  'Condition':                  'အခြေအနေ',
  'Situation':                  'အခြေအနေ',
  'Mood':                       'စိတ်ခံစားချက်',
  'Materials/Data':             'အချက်အလက်',
  'Discussion':                 'ဆွေးနွေးခြင်း',
  'Discussion/Debate':          'ဆွေးနွေးငြင်းခုံခြင်း',
  'Conversation':               'စကားပြောဆိုမှု',
  'Lecture':                    'မိန့်ခွန်း',
  'Speech':                     'မိန့်ခွန်း',
  'Argument':                   'ငြင်းခုံမှု',
  'Consultation':               'တိုင်ပင်ဆွေးနွေးမှု',
  'Decision':                   'ဆုံးဖြတ်ချက်',
  'Promise':                    'ကတိ',
  'Promise/Appointment':        'ကတိ / ချိန်းဆို',
  'Reservation':                'ကြိုတင်မှာယူမှု',
  'Order':                      'မှာယူမှု',
  'Payment':                    'ပေးချေမှု',
  'Purchase':                   'ဝယ်ယူမှု',
  'Return':                     'ပြန်ပေးမှု',
  'Discard':                    'စွန့်ပစ်မှု',
  'Exchange':                   'လဲလှယ်မှု',
  'Praise':                     'ချီးကျူးမှု',
  'Criticism':                  'ဝေဖန်မှု',
  'Report':                     'အစီရင်ခံစာ',
  'Advice':                     'အကြံပေးမှု',
  'Respect':                    'လေးစားမှု',
  'Impression':                 'ထိတွေ့မှု / ပထမအကြိမ် အမြင်',
  'Value/Worth':                'တန်ဖိုး',
  'Price':                      'ဈေးနှုန်း',
  'Cost':                       'ကုန်ကျစရိတ်',
  'Tax':                        'အခွန်',
  'Common sense':               'ယေဘုယျဗဟုသုတ',
  'Responsibility':             'တာဝန်',
  'Duty':                       'တာဝန်',
  'Power':                      'အာဏာ',
  'Position':                   'ရာထူး',
  'Life/Living':                'နေထိုင်မှု',
  'Hobby':                      'ဝါသနာ',
  'Cooking/Cuisine':            'ချက်ပြုတ်ခြင်း',
  'Shopping':                   'စျေးဝယ်ခြင်း',
  'Washing':                    'စီးဆေးလျှောရေခတ်ခြင်း',
  'Cleaning':                   'သန့်ရှင်းရေးလုပ်ခြင်း',
  'Meeting':                    'အစည်းအဝေး',
  'Participation':              'ပါဝင်ခြင်း',
  'Absence':                    'မရှိခြင်း',
  'Invitation':                 'ဖိတ်ကြားမှု',
  'Rejection':                  'ငြင်းကွယ်မှု',
  'Refusal':                    'ငြင်းပယ်မှု',
  'Cancellation':               'ဖျက်သိမ်းမှု',
  'Explanation':                'ရှင်းပြမှု',
  'Question':                   'မေးခွန်း',
  'Question/Problem':           'မေးခွန်း / ပြဿနာ',
  'Answer':                     'အဖြေ',
  'Problem':                    'ပြဿနာ',
  'Prevention':                 'ကြိုတင်တားဆီးမှု',
  'Solution':                   'ဖြေရှင်းချက်',
  'Countermeasure':             'တုံ့ပြန်ရေး အစီအမံ',
  'Denial':                     'ငြင်းဆန်ခြင်း',
  'Confirmation/Check':         'အတည်ပြု / စစ်ဆေး',
  'Contact/Inform':             'ဆက်သွယ်မှု',
  'Realization/Achievement':    'အကောင်အထည်ဖော်ခြင်း',
  'Contribution':               'ပါဝင်ကူညီမှု',
  'Donation':                   'လှူဒါန်းမှု',
  'Support':                    'ပံ့ပိုးမှု',
  'Assistance':                 'အကူအညီ',
  'Benefit/Blessing':           'အကျိုးကျေးဇူး',
  'Debt':                       'ကြွေး',
  'Gift':                       'လက်ဆောင်',
  'Reward':                     'ဆုကြေး',
  'Victory':                    'အနိုင်ရမှု',
  'Active role/Achievement':    'တက်ကြွစွာ ပါဝင်ဆောင်ရွက်မှု',
  'Address':                    'လိပ်စာ',
  'Age':                        'အသက်',
  'Name':                       'နာမည်',
  'Birthday':                   'မွေးနေ့',
  'Schedule/Plan':              'အချိန်ဇယား',
  'Talent':                     'ကျွမ်းကျင်မှု',
  'Forgiveness':                'ခွင့်လွှတ်မှု',
  'Silence':                    'တိတ်ဆိတ်မှု',

  // Verb meanings
  'To eat':                     'စားသည်',
  'To drink':                   'သောက်သည်',
  'To see':                     'ကြည့်သည်',
  'To see/watch':               'ကြည့်သည်',
  'To hear':                    'နားထောင်သည်',
  'To hear/ask':                'နားထောင် / မေးသည်',
  'To read':                    'ဖတ်သည်',
  'To write':                   'ရေးသည်',
  'To draw':                    'ဆွဲသည်',
  'To speak':                   'ပြောသည်',
  'To speak/talk':              'ပြောသည်',
  'To listen':                  'နားထောင်သည်',
  'To say':                     'ပြောသည်',
  'To go':                      'သွားသည်',
  'To come':                    'လာသည်',
  'To return':                  'ပြန်သည်',
  'To return/go home':          'ပြန်သည် / အိမ်ပြန်သည်',
  'To walk':                    'လမ်းလျှောက်သည်',
  'To run':                     'ပြေးသည်',
  'To fly':                     'ပျံသည်',
  'To swim':                    'ရေကူးသည်',
  'To enter':                   'ဝင်သည်',
  'To exit':                    'ထွက်သည်',
  'To exit/go out':             'ထွက်သည်',
  'To stand':                   'ရပ်သည်',
  'To sit':                     'ထိုင်သည်',
  'To sleep':                   'အိပ်သည်',
  'To rest':                    'နားသည်',
  'To work':                    'အလုပ်လုပ်သည်',
  'To study':                   'ပညာသင်သည်',
  'To play':                    'ကစားသည်',
  'To play with':               'ကစားသည်',
  'To buy':                     'ဝယ်သည်',
  'To sell':                    'ရောင်းသည်',
  'To give':                    'ပေးသည်',
  'To take':                    'ယူသည်',
  'To receive':                 'ခံယူသည်',
  'To receive/take':            'ခံယူသည်',
  'To send':                    'ပို့သည်',
  'To deliver':                 'ပေးပို့သည်',
  'To pay':                     'ပေးချေသည်',
  'To save':                    'သိမ်းဆည်းသည်',
  'To lend':                    'ငှားသည်',
  'To borrow':                  'ငှားရမ်းသည်',
  'To meet':                    'တွေ့သည်',
  'To call':                    'ခေါ်သည်',
  'To wait':                    'စောင့်သည်',
  'To use':                     'သုံးသည်',
  'To make':                    'လုပ်သည်',
  'To make/create':             'လုပ်သည် / ဖန်တီးသည်',
  'To think':                   'ထင်သည်',
  'To think/consider':          'တွေးသည်',
  'To know':                    'သိသည်',
  'To feel':                    'ခံစားသည်',
  'To forget':                  'မေ့သည်',
  'To remember':                'မှတ်မိသည်',
  'To remember/memorize':       'မှတ်မိသည်',
  'To dream':                   'အိပ်မက်မက်သည်',
  'To live/reside':             'နေထိုင်သည်',
  'To live/make a living':      'နေထိုင်သည် / အသက်မွေးသည်',
  'To travel':                  'ခရီးသွားသည်',
  'To move':                    'ပြောင်းရွှေ့သည်',
  'To visit':                   'သွားရောက်လည်ပတ်သည်',
  'To teach':                   'သင်ပေးသည်',
  'To learn':                   'သင်ယူသည်',
  'To ask':                     'မေးသည်',
  'To answer':                  'ဖြေသည်',
  'To open':                    'ဖွင့်သည်',
  'To close':                   'ပိတ်သည်',
  'To push':                    'တွန်းသည်',
  'To pull':                    'ဆွဲသည်',
  'To lift':                    'ချီသည်',
  'To carry':                   'သယ်သည်',
  'To throw':                   'ပစ်သည်',
  'To catch':                   'ဖမ်းသည်',
  'To begin':                   'စတင်သည်',
  'To end':                     'ပြီးဆုံးသည်',
  'To end/finish':              'ပြီးဆုံးသည်',
  'To continue':                'ဆက်လက်သည်',
  'To stop':                    'ရပ်သည်',
  'To start':                   'အစပြုသည်',
  'To finish/complete':         'ပြီးစီးအောင်ဆောင်ရွက်သည်',
  'To arrive':                  'ရောက်သည်',
  'To arrive/reach':            'ရောက်ရှိသည်',
  'To leave':                   'ထွက်ခွာသည်',
  'To change':                  'ပြောင်းသည်',
  'To decide':                  'ဆုံးဖြတ်သည်',
  'To choose/select':           'ရွေးချယ်သည်',
  'To collect/gather':          'စုဆောင်းသည်',
  'To scatter':                 'ဖြန့်ကြဲသည်',
  'To separate':                'ခွဲသည်',
  'To compare':                 'နှိုင်းယှဉ်သည်',
  'To increase':                'တိုးသည်',
  'To decrease':                'လျော့သည်',
  'To stay':                    'ဆက်ရှိနေသည်',
  'To throw away':              'စွန့်ပစ်သည်',
  'To pick up':                 'ကောက်ယူသည်',
  'To keep':                    'သိမ်းသည်',
  'To find':                    'ရှာတွေ့သည်',
  'To break':                   'ကွဲသည် / ဖျက်သည်',
  'To break/destroy':           'ဖျက်ဆီးသည်',
  'To build':                   'တည်ဆောက်သည်',
  'To build/construct':         'တည်ဆောက်သည်',
  'To fix':                     'ပြင်သည်',
  'To fix/repair':              'ပြင်ဆင်သည်',
  'To repair':                  'ပြင်ဆင်သည်',
  'To destroy':                 'ဖျက်ဆီးသည်',
  'To drop':                    'ကျောငြိမ်းသည်',
  'To clean':                   'သန့်ရှင်းရေးလုပ်သည်',
  'To wash':                    'ဆေးသည်',
  'To iron':                    'ပုဆိုးသတ်သည်',
  'To dry':                     'သွေ့ခြောက်သည်',
  'To cook':                    'ချက်ပြုတ်သည်',
  'To look up/investigate':     'ရှာဖွေစစ်ဆေးသည်',
  'To investigate':             'စစ်ဆေးသည်',
  'To plan':                    'စီစဉ်သည်',
  'To plant':                   'စိုက်သည်',
  'To harvest':                 'ရိတ်သိမ်းသည်',
  'To cultivate/foster':        'ပျိုးထောင်သည်',
  'To protect':                 'ကာကွယ်သည်',
  'To hide':                    'ဝှက်သည်',
  'To shine':                   '빛ဖင်ပြောင်တောက်သည်',
  'To disappear':               'ပျောက်ကွယ်သည်',
  'To stand out':               'ထင်ရှားသည်',
  'To raise/bring up':          'ပြုစုပျိုးထောင်သည်',
  'To challenge':               'စိန်ခေါ်သည်',
  'To avoid':                   'ရှောင်ကြဉ်သည်',
  'To accept':                  'လက်ခံသည်',
  'To refuse':                  'ငြင်းပယ်သည်',
  'To quit':                    'ထွက်သည်',
  'To postpone':                'ရွှေ့ဆိုင်းသည်',
  'To delay':                   'နောက်ကျသည်',
  'To cancel':                  'ဖျက်သိမ်းသည်',
  'To confirm':                 'အတည်ပြုသည်',
  'To add':                     'ထည့်သည်',
  'To urge/encourage':          'တိုက်တွန်းသည်',
  'To be engaged in':           'ပါဝင်ဆောင်ရွက်သည်',
  'To observe':                 'လေ့လာကြည့်ရှုသည်',
  'To be moist/profit':         'စိုပြေသည်',
  'To flow':                    'စီးဆင်းသည်',
  'To freeze':                  'ခဲသည်',
  'To cover':                   'ဖုံးသည်',
  'To overturn/reverse':        'ပြောင်းပြန်လှန်သည်',
  'To regard as':               'မှတ်ယူသည်',
  'To look at':                 'ကြည့်သည်',
  'To ignore':                  'လစ်လျူရှုသည်',
  'To copy':                    'ကူးသည်',
  'To differ':                  'ကွာခြားသည်',
  'To resemble':                'တူသည်',
  'To make a mistake':          'မှားသည်',
  'To get used to':             'အသားကျသည်',
  'To convey/tell':             'ပြောကြားသည်',
  'To endure':                  'ခံနိုင်ရည်ရှိသည်',
  'To escape/be exempt':        'လွတ်မြောက်သည်',
  'To be surprised':            'အံ့သြသည်',
  'To be angry':                'ဒေါသထွက်သည်',
  'To be correct':              'မှန်ကန်သည်',
  'To laugh':                   'ရယ်သည်',
  'To cry':                     'ငိုသည်',
  'To relax':                   'ပြေလျော့သည်',
  'To worry':                   'စိတ်ပူသည်',
  'To give up':                 'စွန့်လွှတ်သည်',
  'To try':                     'ကြိုးစားသည်',
  'To understand':              'နားလည်သည်',
  'To head toward':             'ဦးတည်သွားသည်',
  'To be moist/profit':         'စိုပြေသည်',

  // Missed on first pass
  'Caution/Attention':          'သတိထားခြင်း',
  'Fun':                        'အပျော်ဖြစ်သော',
  'Funny':                      'ရယ်စရာ',
  'Honest/Obedient':            'ရိုးသားသော',
  'Magnificent/Grand':          'ကြီးကျယ်ခမ်းနားသော',
  'Mean':                       'ယုတ်မာသော',
  'Prediction':                 'ကြိုတင်ခန့်မှန်းချက်',
  'Proud':                      'မာနကြီးသော',
  'Quiet':                      'တိတ်ဆိတ်သော',
  'Regrettable/Unfortunate':    'ဝမ်းနည်းစရာ',
  'Relationship/Connection':    'ဆက်ဆံရေး',
  'Rest':                       'နားခြင်း',
  'Serious/Grave':              'ဆိုးရွားသော',
  'Sign/Symptom':               'လက္ခဏာ',
  'Stubborn':                   'ခေါင်းမာသော',
  'To have/hold':               'ကိုင်သည် / ရှိသည်',
};

function translateOption(opt) {
  if (!opt) return opt;
  const trimmed = opt.trim();
  return EN_TO_MM[trimmed] !== undefined ? EN_TO_MM[trimmed] : opt;
}

async function translateOptions() {
  try {
    console.log('🔤 Fetching all quiz questions...');
    const { rows } = await pool.query('SELECT id, option_a, option_b, option_c, option_d FROM quiz_questions');

    let updated = 0;
    let unchanged = 0;
    const unmatched = new Set();

    for (const row of rows) {
      const na = translateOption(row.option_a);
      const nb = translateOption(row.option_b);
      const nc = translateOption(row.option_c);
      const nd = translateOption(row.option_d);

      if (na !== row.option_a || nb !== row.option_b || nc !== row.option_c || nd !== row.option_d) {
        await pool.query(
          'UPDATE quiz_questions SET option_a=$1, option_b=$2, option_c=$3, option_d=$4 WHERE id=$5',
          [na, nb, nc, nd, row.id]
        );
        updated++;
      } else {
        unchanged++;
      }

      // Collect unmatched English-looking options
      [row.option_a, row.option_b, row.option_c, row.option_d].forEach(o => {
        if (o && /^[A-Za-z\s\/\(\)\-\.,\"'!?]+$/.test(o.trim()) && EN_TO_MM[o.trim()] === undefined) {
          unmatched.add(o.trim());
        }
      });
    }

    console.log(`\n✅ Updated:   ${updated} questions`);
    console.log(`⏭️  Unchanged: ${unchanged} questions`);

    if (unmatched.size > 0) {
      console.log(`\n⚠️  Unmatched English options (${unmatched.size}):`);
      [...unmatched].sort().forEach(u => console.log('  -', u));
    } else {
      console.log('🎉 All English options translated successfully!');
    }

  } catch (err) {
    console.error('❌ Error:', err.message);
    console.error(err.stack);
  } finally {
    await pool.end();
  }
}

translateOptions();
